### ISSUE TITLE
Map options don't seem to work

### ISSUE THREAD

**Issue by SilasPeters** [ichim/LeafletForBlazor-NuGet#1]
Hi there @ichim! I love your package, but I believe something's not working right.

I declared my map like this:
```C#
<Map
  width="@width" 
  height="@height"
  Parameters="@parameters"
  Options="@map_options"
  GeoJSON_urls="@urls.ToArray()"
  onLoadMap="@OnLoadMap"
  onMapClick="@OnMapClick"
  onZoomChange="@OnZoomChange">
</Map>
```

And in my ``@code`` block, I have this:
```C#
Map.MapOptions map_options = new()
{
  keyboard_navigation_options = new() {keyboard = false}
};
```

Yet, I can still use my keyboard (arrow buttons and such.) Overriding other options also does not seem to matter; it's as if everything is set to ``true`` by default.

**Comment by ichim** [comment]
Hello sir,

I saw it, thank you very much for the report!


Thanks a lot for using package!

From: Silas Peters ***@***.***>
Sent: Sunday, February 26, 2023 2:07 PM
To: ichim/LeafletForBlazor-NuGet ***@***.***>
Cc: Laurențiu Ichim ***@***.***>; Mention ***@***.***>
Subject: [ichim/LeafletForBlazor-NuGet] Map options don't seem to work (Issue #1)


Hi there @ichim<https://github.com/ichim>! I love your package, but I believe something's not working right.

I declared my map like this:

<Map

  ***@***.***"

  ***@***.***"

  ***@***.***"

  ***@***.***_options"

  ***@***.***()"

  ***@***.***"

  ***@***.***"

  ***@***.***">

</Map>

And in my @code block, I have this:

Map.MapOptions map_options = new()

{

  keyboard_navigation_options = new() {keyboard = false}

};

Yet, I can still use my keyboard (arrow buttons and such.) Overriding other options also does not seem to matter; it's as if everything is set to true by default.

**Comment by ichim** [comment]
Hello for every one,

This config option is not completed. Sorry
