### ISSUE TITLE
Cannot user movePoint(coordinate.ToArray(), PointIcon icon, PointTooltip tooltip);

### ISSUE THREAD

**Issue by khairulazmimatesa** [ichim/LeafletForBlazor-NuGet#12]
Maximum call stack size exceeded RangeError: Maximum call stack size exceeded at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658) at addPointIconAndTooltip (http://localhost:5049/_content/LeafletForBlazor/RealTime/Map.js:1:2658)

**Comment by ichim** [comment]
Hello sir,
Which is the content of the coordinates list, controlul etc

**Comment by khairulazmimatesa** [comment]
private async Task MoveLocation() {
        await Task.Delay(TimeSpan.FromMilliseconds(300));

        RealTimeMap.PointIcon icon = new RealTimeMap.PointIcon() {
                iconUrl = "images/bus.png",
                iconSize = new int[] { 40, 40 },
                iconAnchor = new int[] { 20, 20 },
            };

        RealTimeMap.PointTooltip tooltip = new RealTimeMap.PointTooltip() {
                content = $"Bus No : {Model.BusNo} <br/> Location : {Model.BusLocation}",
                opacity = 0.7,
                permanent = true
            };

        var coordinate = new List<double>() { Model.latitude, Model.longitude };

        await realTimeMap.movePoint(coordinate.ToArray(), icon, tooltip);

    }


Is use like this.

**Comment by ichim** [comment]
Please more details!
This method crash after how many iterations?

**Comment by khairulazmimatesa** [comment]
![image](https://github.com/ichim/LeafletForBlazor-NuGet/assets/77063785/68a5f800-bfb9-4fc9-a42e-3cda18531fe5)

hi sir, crash after first iteration. i tested realTimeMap.movePoint(coordinate.ToArray(), symbol, tooltip); no issue.

but after i tried to use icon eg: realTimeMap.movePoint(coordinate.ToArray(), icon, tooltip); got error as shown in image. 

then i change to realTimeMap.movePoint(coordinate.ToArray(), icon); got no problem. 

i cannot used method movePoint(coordinate.ToArray(), icon, tooltip);

or can you show me example to user icon in movePoint instead of symbol?

**Comment by DanielEggers** [comment]
Hello Laurentiu,
this bug is caused by wrong function invocation in the Maps.js
Instead of

export const addPointIconAndTooltip = o => { addPointIconAndTooltip(o, map, LeafletCore) };

it should be 

export const addPointIconAndTooltip = o => { a(o, map, LeafletCore) };

I would like to create a pull request, but can't find the source code. This repository only includes sample code.
Where can I find the source code?

**Comment by mcooke-mdkl** [comment]
I am experiencing this issue also.

**Comment by ichim** [comment]
https://github.com/ichim/LeafletForBlazor-NuGet
This version, 2.2.2.2, rezolve this bug. Sorry for delay.

**Comment by khairulazmimatesa** [comment]
Thanks sir for the fix. you're the best
