### ISSUE TITLE
Map Size or Stretch

### ISSUE THREAD

**Issue by condairteam** [ichim/LeafletForBlazor-NuGet#14]
Hi Laurentiu, 
Thank you  for the great package!
Is there a chance to resize the Map canvas size in real time to fit the browser window, or can we use css style such as Style="width: 97vw; height: 92vh;" to stretch it?

Thanks in advance
Alex

**Comment by ichim** [comment]
Hello,

I understand the problem, at the moment not. The only possibility is to encapsulate (I think) the RealTimeMap control in another html component. **I will consider this aspect to improve the control**

**Comment by condairteam** [comment]
> Hello,
> 
> I understand the problem, at the moment not. The only possibility is to encapsulate (I think) the RealTimeMap control in another html component. **I will consider this aspect to improve the control**

Thank you Sir!

**Comment by ichim** [comment]
> > Hello,
> > 
> > I understand the problem, at the moment not. The only possibility is to encapsulate (I think) the RealTimeMap control in another html component. **I will consider this aspect to improve the control**
> 
> Thank you Sir!

Thank you for using the package,

Laurentiu

**Comment by ClayJay3** [comment]
Hi, I was wondering if support for this feature has been added yet. Currently, if I try to set the map width and height to a percentage (`<RealTimeMap height="100%" width="100%"></RealTimeMap>
`) doesn't show up. I have also tried setting the width and height of a parent HTML component and it doesn't seem to work either.

**Comment by ClayJay3** [comment]
@ichim

**Comment by ichim** [comment]
Hello sir,
I suppose you want to fill the page with RealTimeMap.
It is not the same as in html.

**Comment by ClayJay3** [comment]
Hello, thanks for the reply! Will this method of sizing the map only work on initial load, or can I use this for a page that will be dynamically resized by the user? I have a Blazor component that the map will be contained in, and I need the component and map to scale to the space available on the page depending on what other components are on the page. This currently works for the component, but not the map.

**Comment by ichim** [comment]
Hello sir,
Both scenarios. It can be sized/resized according to other elements in the map:

  `<RealTimeMap height="calc(100vh - 6rem)" width="calc(100vw - 40rem)" Parameters="@parameters"></RealTimeMap>`

... where 40rem is width of other page item...for example

**Comment by rfarkv** [comment]
Hi!
I'm using variables to set height and weight, something like this:

    string mapaHeight = "100vh";
    string mapaWidth = "100vw";

`        <RealTimeMap @ref="realTimeMap"  OnMouseUpMap="onMouseUpMap" OnClickMap="onClickMap" OnAfterMapLoaded="@AfterMapLoaded" OnZoomLevelEndChange="@OnZoomLevel" Parameters="parameters" height=@mapaHeight width=@mapaWidth ></RealTimeMap>
`
Then i have a method that do some stuff and calculate the new site of the map, i then change the value of the variables:
```
public void string ChangeMapSize()
{
        ...
        mapaWidth = "50vw";
        mapaHeight = 50vh";

       StateHasChanged();
}
```
The problem is the map is not changing, at all.
I change both variables, and call StateHasChanged, nothing happens. Am i missing something?
