### ISSUE TITLE
Map zooming out when Geometric.Points.moveTo(point);

### ISSUE THREAD

**Issue by Franstio** [ichim/LeafletForBlazor-NuGet#15]
Hi Laurentiu,
Thank you for the great package!
This is my very first time open up new issue so sorry if i have made some mistake when writing this. I have some some issue(?) when using Geometric.Points.moveTo(point) the realtime map always zoom out automatically. is that the expected behaviour or is there any way to prevent it from zoom out automatiaclly when using   Geometric.Points.moveTo function? Thanks in advance

**Comment by ichim** [comment]
Hello sir,

Starting with the last version (2.0.2.2) I added the property: **changeExtentWhenMovingPoints** (boolean)

`realTimeMap.Geometric.Points.changeExtentWhenMovingPoints = false;`

This property prevents moving the current view of the map to the maximum extent of the points.

Laurentiu

**Comment by Franstio** [comment]
Thank you for your response, Laurentiu.
The zoom out when using moveTo is solved but when using Geometric.Points.add it still happen. is there any way to stop it when using add function?

**Comment by ichim** [comment]
No, sir. At this moment it is not possible to prevent the change of the current view on the add() method. However, I will take into account the request for the next version

**Comment by Franstio** [comment]
Alright then, thank you very much and have a nice day sir.

**Comment by ichim** [comment]
Thank you and have a nice day.
