### ISSUE TITLE
Default Marker

### ISSUE THREAD

**Issue by DTemeroso** [ichim/LeafletForBlazor-NuGet#18]
Is normal to appear a defaut marker after i inicialize the map?

I use the code from the example that is provided.

![image](https://github.com/ichim/LeafletForBlazor-NuGet/assets/160488451/75fb17ac-a0f4-4dad-851e-481b34cb90dd)

[Example](https://github.com/ichim/LeafletForBlazor-NuGet/tree/main/AddMapToBlazorPage)

**Comment by ichim** [comment]
Hello sir,

It depends on the example used. Can you tell me what the VS project is?

**Comment by DTemeroso** [comment]
is is the one in the link

**Comment by ichim** [comment]
Thank you for using the package!
