### ISSUE TITLE
GeoJson on Realtimemap

### ISSUE THREAD

**Issue by condairteam** [ichim/LeafletForBlazor-NuGet#21]
Hi Sir!

Your package is so amazing so thank you for your hard work! Just a quick question. Is there a chance to use/import geojson data into Realtimemap instead/beside of regular MAP?
Also i have noticed that on realtimemap there is no way to disable the zoomin function when i doubleclicking on the map. Could you help me out how to disable this behavior in an event?

Thank you Sir!

Alex

**Comment by ichim** [comment]
Hello sir,

Both functionalities will be available: disable zoom in as well as loading GeoJSON files.

Real Time Map is optimized to work with a large number of points whose position is updated in real time.

Thank you

**Comment by condairteam** [comment]
Thank you so much!

**Comment by condairteam** [comment]
Hi Sir!
It's me again with just a quick one. Is there an option to change the name of layers and the color of the lines, polygons etc. on the map? So far everything is blue for me. (and maybe just for me, but there is a symbol in Bucharest that i can't remove it.)

Thank you for your hard work Sir!
Alex
![image](https://github.com/ichim/LeafletForBlazor-NuGet/assets/83860587/716b69cc-b763-4d50-9c8a-38353f2058a8)

**Comment by ichim** [comment]
To display the names of the layers in the Layer Control, you must set the property:

```
Map.LoadParameters parameters = new Map.LoadParameters()
{
    anyway_overlay_layers_control = true
}
```

**Comment by condairteam** [comment]
> To display the names of the layers in the Layer Control, you must set the property:
> 
> ```
> Map.LoadParameters parameters = new Map.LoadParameters()
> {
>     anyway_overlay_layers_control = true
> }
> ```

Yes I have already done that. i am trying to figure it out where that guid comes from.

**Comment by ichim** [comment]
I will try to do it as soon as possible, sir.

**Comment by MichaelHochriegl** [comment]
I'm currently evaluating some solutions for a work project I have where I have to render GeoJSON and pretty much only GeoJSON, so I don't have to render a "real" map, only a hodgepodge of points, lines and curved lines.

Is there a rough ETA on when GeoJSON drawing is available on the RTM? Or is there any help I can offer?

**Comment by ichim** [comment]
Hello sir,

Probably the next version of RealTimeMap will also have GeoJSON data loading

**Comment by ichim** [comment]
Hello sir,

The new version of the package, 2.0.6.4, provides DataFromGeoJSON. With this new class, you can add spatial data from GeoJSON file.

**Comment by condairteam** [comment]
Hi Sir,

Thank you sir, awesome job! 👍

The LeafletForBlazor.RealTime.data.geojson.FromGeoJSON(string[] urls) function works only in webassembly mode, but doesnt in server-side rendering mode. There is no error, but the map is empty. 
Your sample is working fine, but that is webassembly. Could you look after why is that? 

Thank you so much,
Alex

**Comment by ichim** [comment]
Hello, 

It must work!  Change the rendering mode

**Comment by condairteam** [comment]
Hi,
Yeah i know  you're right, but my project's rendermode is InteractiveServer only and cant use webassembly (or InteractiveWebassembly), because of policy issues. Right now  i am trying figurite out, how i can make it works in Serverside mode. All of your previous codes are working as intended but the FromGeoJSON(string[] urls) function.

Apologies for the inconvenience and thanks advance all your help ,
Alex

**Comment by ichim** [comment]
Sorry sir,

I think it is:

Geometric.

**Comment by ichim** [comment]
New example code:

https://github.com/ichim/LeafletForBlazor-NuGet/tree/main/RTM%20and%20GeoJSON/config%20tooltip%20from%20file

**Comment by condairteam** [comment]
It is working In webassembly, but isnt in serverside.

I think this code doesnt work in serverside mode in your FromGeoJSON class.

```c
 public async Task addFromFiles(string[] urls)
    {
      HttpClient client = new HttpClient();
      string raw = "";
    ...
       raw = await client.GetStringAsync(url);   //this line doesnt fire in serverside mode, only in webassembly, therefore that is why the map is empty for me
     }
```

I think maybe you should use this
```c
 public async Task addFromFiles(string[] urls)
    {
        using var httpClientHandler = new HttpClientHandler();
        httpClientHandler.ServerCertificateCustomValidationCallback =
            (_, _, _, _) => true;
        using var client = new HttpClient(httpClientHandler);
        raw = client.GetStringAsync(url).Result;
    ...
}

```

Thank you sir all of your work!  👍

**Comment by ichim** [comment]
Hello sir,

Thank you very much for what you told me!

**Comment by weismantelf** [comment]
Hello,
I just facing the same issue. The problem is that the function

`public async Task addFromFiles(string[] urls)`

is using the HttpClient. This is working when you are using http, but
not when you are using https. In that case the HttpClient is throwing
an exception.

So for this case the proposal of condairteam is working.

Is it possible to implement this ?
