### ISSUE TITLE
Behaviour zoom level after adding points

### ISSUE THREAD

**Issue by ehilgen** [ichim/LeafletForBlazor-NuGet#25]
Hi,

I really like your package, if i add a map i can set the base coordinates and an zoom level. if i display the map is zooms correctley.
After an OnAfterMapLoaded i load the StreamPoints to the map, after this it zooms to the area around the points in stead of the maps zoomlevel and cooridinates. Is this standard behavour, ir can i set a setting to oveeride it?

Thank you,

Regards,

Etienne

**Comment by ichim** [comment]
Hello sir,
You can prevent this behavior if you add points using add method and set false the changeExtentWhenAddPoints  property:

`Geometric.Points.changeExtentWhenAddPoints = false`

**Comment by ehilgen** [comment]
Great this works, thank you!
