### ISSUE TITLE
Tooltip content don't format with point attributes when tooltip is not permanent

### ISSUE THREAD

**Issue by JohannAtExp** [ichim/LeafletForBlazor-NuGet#26]
If you setup a point apparence pattern with tooltip with permanent=false, it the tooltip content shows without formatting the content with point attributes on mouse hover.

Repro steps:
- open the "RTM Points Tooltips" solution
- edit the "Index.Razor" page as well:
![image](https://github.com/ichim/LeafletForBlazor-NuGet/assets/86784133/0d18087a-c8de-4a4d-9213-196ac27eb5f4)
- When you run the map, the non permanent tooltips will show as well
![image](https://github.com/ichim/LeafletForBlazor-NuGet/assets/86784133/c88d7be9-e043-4a09-a17b-463d69baade6)

**Comment by ichim** [comment]
Hello sir,

This is a bug!
I apologize for the bug, I will fix this bug!

Thanks for the report!

**Comment by ichim** [comment]
Hello sir,

Version 2.0.4.4 of the LeafletForBlazor package fixes the bug you reported (it will be available in a few minutes).

https://www.nuget.org/packages/LeafletForBlazor/2.0.4.4#readme-body-tab
