### ISSUE TITLE
realTimeMap.Geometric.DisplayPolygonsFromArray Delete Method missing

### ISSUE THREAD

**Issue by groehm** [ichim/LeafletForBlazor-NuGet#28]
realTimeMap.Geometric.DisplayPolygonsFromArray works great, but I'm not fidning a "delete" method for being able to remove them.

**Comment by ichim** [comment]
You are right, I will add the delete method for the Display Polygons From Array class as well.
Thank you!

**Comment by ichim** [comment]
Hello,
I uploaded a new version (2.0.4.6) that provides the deleteAll() method on the DisplayPolygonsFromArray class.

**Comment by groehm** [comment]
Tested and working great. Thank you for the incredibly fast update to this as well as this incredible package!
