### ISSUE TITLE
GeoPoints not from file - question

### ISSUE THREAD

**Issue by K2-Software** [ichim/LeafletForBlazor-NuGet#3]
Is there any possibility that we will use a list of objects or a JSON string, not a URL to json file to display custom points on map?

**Comment by ichim** [comment]
Not for this moment, sorry!

From: K2-Software ***@***.***>
Sent: Tuesday, March 7, 2023 3:57 PM
To: ichim/LeafletForBlazor-NuGet ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ichim/LeafletForBlazor-NuGet] GeoPoints not from file - question (Issue #3)


Is there any possibility that we will use a list of objects or a JSON string, not a URL to json file to display custom points on map?

**Comment by ichim** [comment]
Hello,
Starting with 1.2.3 version, you can load JSON string data (GEO JSON data).
Thanks a lot!
