### ISSUE TITLE
.Net Core 8 Support

### ISSUE THREAD

**Issue by BusonRamesh** [ichim/LeafletForBlazor-NuGet#32]
Hi,

Will it support for .Net Core 8

**Comment by ichim** [comment]
Hello sir,

Yes, it can be used in the .NET 8 app.

**Comment by BusonRamesh** [comment]
Map is not rendering when created in Blazor 8.0 Server App. also no error message in console too.

**Comment by ichim** [comment]
Hello sir,

Sorry for delay!

In the repository you can also find projects made with .NET 8, for example:

**Comment by BusonRamesh** [comment]
Hi sir,

Do you have any examples working on server side application. as the example stated by you was webassembly project.

**Comment by ichim** [comment]
Hello again,

Not at this time.  But it should be the same implementation.

**Comment by BusonRamesh** [comment]
Hi,

Changed the render mode, now its working fine. Thanks
