### ISSUE TITLE
Source availability

### ISSUE THREAD

**Issue by bouskdav** [ichim/LeafletForBlazor-NuGet#33]
Hi, thanks for this project! Appologies for my ignorance, perhaps, but I'm currently only investigating which wrappers around Leaflet are available. 

Am I right, that there is no source available for this package? Therefore e.g. integration of other plugins might not be possible without your help and further developments depend solely on you?

Thanks! Regards!
David

**Comment by ichim** [comment]
Hello sir,

For the moment, yes.  The first versions exposed the entire project.  Then, I decided to postpone making the project available until I manage to bring it to an acceptable form.

What I want is to be able to offer a package that is very easy to use and fully integrated with Blazor.  I tried to minimize the number of requests and client-server calls and more in terms of project logic.

The first versions of the package "offered" many requests and calls. Sorry!

**Comment by bouskdav** [comment]
Thanks for your response! Yes, that's understandable. 

Also I wasn't able to find any valid license thus it seems kinda dangerous to use this package (in something more than internal tool). Anyway it's pretty obvious that there's a big effort in this package so I stay in touch for further versions :)

Good job!
