### ISSUE TITLE
Map container not found

### ISSUE THREAD

**Issue by martin-hirsch** [ichim/LeafletForBlazor-NuGet#38]
Hello there,

I have trouble upgrading from `2.0.2.4` to `2.0.6.8`. In version `2.0.2.4` everything worked as expected with no issues at all. I was very happy to find your repository. :-) 

I am confident that I followed your example here: https://github.com/ichim/LeafletForBlazor-NuGet/tree/main/RTM%20and%20GeoJSON/working%20with%20Files/GeoJSON%20from%20file . I am not even using the latest versions, but the exact same as in the example.

Any help would be appreciated. <3

Few things to mention here: 
- I'm running webassembly like you, but in docker.
- LeafletForBlazor is inside a component library
- dotnet 8.0.6

So I have a `Shell.csproj` referencing a `Maps.csproj`

The exception occurs here:

Error: Map container not found.

Map.js:1093

```js
_initContainer: function (id) {
		var container = this._container = DomUtil.get(id);

		if (!container) {
			throw new Error('Map container not found.');
		} else if (container._leaflet_id) {
			throw new Error('Map container is already initialized.');
		}

		DomEvent.on(container, 'scroll', this._onScroll, this);
		this._containerId = Util.stamp(container);
	},
```

One more thing: The exception occurs only in Docker. When I start the application locally, everything works fine.

## Before

```html
<RealTimeMap @ref="_realTimeMap" Parameters="@Parameters"></RealTimeMap>
```

## After

```html
<RealTimeMap width="460px" height="460px"  Parameters="@Parameters" OnAfterMapLoaded="@OnAfterMapLoaded" />
```

**Comment by ichim** [comment]
Hello sir,
I'm not sure what to think about, but I'll take them one by one: 

1. uploading data from GeoJSON files appeared with version 2.0.6.6.  You must make sure that you do not have an older version of the package;  

2. can another sample application, other than working with GeoJSON data, run on docker? If the answer it "yes", it is possible an error generated by the addresses to the GeoJSON files (https://...);

**Comment by martin-hirsch** [comment]
Thanks for the fast response!

1. I am using `2.0.6.8` now :-) I think I did not copy it from the `.csproj` and did not remember the correct number.
2. I did not yet try, but I assume the issue is not caused by the GeoJSON files? The map also does not load when I try to render it empty.

What do you think?

**Comment by ichim** [comment]
Can you tell me what error it returns?

**Comment by martin-hirsch** [comment]
_Map container not found_

You can find it in the code snippet.

**Comment by ichim** [comment]
I tried to catch all the errors in the code.  The error you mentioned, right from the start, is generated by the Leaflet API.  I do not rule out that this is generated in the cascade from my code!

**Comment by martin-hirsch** [comment]
Right, to me it looks like leaflet initialises (runs the script) before the container is rendered. So that there is no id 🧐

**Comment by ichim** [comment]
I understand. For the next version I will also add RFC from String

**Comment by ichim** [comment]
I understand. For the next version I will also add data (RFC format) from string

**Comment by martin-hirsch** [comment]
Oh I would like that very much.
