### ISSUE TITLE
OnMouseMove event

### ISSUE THREAD

**Issue by Hayame** [ichim/LeafletForBlazor-NuGet#40]
Hi, I would like to implement the ability to draw a line on a map. The user selects a starting point, and then a line is drawn from that point. The shape of this line will update as the mouse moves. Is there a way to hook into the OnMouseMove event to get current mouse location?

**Comment by ichim** [comment]
Hello sir,

Both, OnMouseDownMap and OnMouseDownMap return location of the click point:


//Blazor Page <RealTimeMap height="620px" width="820px" OnMouseDownMap="onMouseDownMap"></RealTimeMap> //Code block @code{ public void onMouseDownMap(RealTimeMap.ClicksMapArgs value) { //where value.sender is RealTimeMap control reference Console.WriteLine(value.location.latitude); Console.WriteLine(value.location.longitude); } }

**Comment by Hayame** [comment]
Than you for an answer. Yeah, these one I know, but the idea is to show user how long is the line he wants to draw and how it will look on the map, so I need cords of mouse in real time to redraw the line on a mouse move, not only when he clicks on the map

**Comment by ichim** [comment]
Hello sir,
I understand, in this case a new OnMouseMoveMap event would be needed.  This event will need to return location on mouse movement.
I will  add this event on future version(s).

**Comment by ichim** [comment]
Hello sir,
Version 2.0.8.8 is available. In this version you will find the OnMouseMove event (issue #40).

https://www.nuget.org/packages/LeafletForBlazor/2.0.8.8
