### ISSUE TITLE
AppearanceOnType 

### ISSUE THREAD

**Issue by paoc77** [ichim/LeafletForBlazor-NuGet#46]
Hi, thanks for this great component, this code should work ?  i can't customize the marker with an icon, thanks

realTimeMap.Geometric.Points.AppearanceOnType(item => item.type == "car").pattern = new RealTimeMap.PointIcon()
    {
        iconUrl = "images/car.png"
    };

**Comment by paoc77** [comment]
Hello, thanks for answer, still not working, i changed the url of the image, i can see it in the browser
this is a fragment of my code, the points are ok in the map, icon still missing for type="car"

`foreach(var position in data.positions)
{
    var device = _devices.Where(d => d.Id == position.DeviceId).FirstOrDefault();

    streamPoints.Add(new RealTimeMap.StreamPoint()
    {
        guid = Guid.Parse(Guid.NewGuid().ToString()),
        timestamp = DateTime.Now,
        latitude = position.Latitude,
        longitude = position.Longitude, 
        type = device.Category,
        value = device.Name
    });                
}

if (realTimeMap != null)
{
    realTimeMap.Geometric.Points.AppearanceOnType(item => item.type == "car").pattern = new RealTimeMap.PointIcon()
        {
            iconUrl = "https://localhost:7073/images/car.png",
            iconSize = [32,32]
        };
        
         await realTimeMap.Geometric.Points.upload(streamPoints);
}`

**Comment by ichim** [comment]
Are the coordinates correct? ... latitude and longitude
To check, you can use google maps ...

**Comment by paoc77** [comment]
Hi thanks for your support, i check everything, the PointTooltip is working fine, the PointSymbol works fine, the PointIcon is not working.

```
 realTimeMap.Geometric.Points.AppearanceOnType(item => true).pattern = new RealTimeMap.PointTooltip()
     {
         content = "<h6>${value}</h6>${type}",
         opacity = 0.8,
         permanent = false
     };

 realTimeMap.Geometric.Points.AppearanceOnType(item => true).pattern = new RealTimeMap.PointIcon()
     {
         iconUrl = "https://localhost:7073/images/car.png",
         iconSize = [32, 32],
         iconAnchor = [10, 10]
     };

 await realTimeMap.Geometric.Points.upload(streamPoints);
```

![MapError](https://github.com/user-attachments/assets/485f13fc-6069-4ccd-bc3b-12a51fd44eee)

**Comment by ichim** [comment]
Sir, I don't know what to think!

You can try to change AppearanceOnType() method with Appearance()?

Both change symbols of points, but ApoearanceOnType allow to control more about appearance (ex. visibility on scale level).

**Comment by paoc77** [comment]
Hi please take a look at this code, realTimeMap.movePoint works ok and shows the custom icon (pin)
Points.upload(pointsStart,true,icon)  ignores the icon, no matter what you do always render circleMarker, looks like a bug my friend.

 ```
RealTimeMap.PointIcon icon = new RealTimeMap.PointIcon()
 {
     iconUrl = "https://localhost:7073/images/car.png"
 };

 realTimeMap.Geometric.Points.Appearance(item => item.type == "Intervention crew").pattern = icon;

 List<RealTimeMap.StreamPoint> pointsStart = new List<RealTimeMap.StreamPoint> {
   new RealTimeMap.StreamPoint()
     {
         guid = Guid.NewGuid(),
         type = "Intervention crew",
         value = "5 seats",
         latitude = 44.45028925827577,
         longitude =  26.10629452317551
     }
 };

 await realTimeMap.movePoint([44.45028925827577, 26.10629452317551],icon);
 await realTimeMap.Geometric.Points.upload(pointsStart,true,icon);
```

![image](https://github.com/user-attachments/assets/4dc2682f-6178-4def-801c-59c35f70c59f)

**Comment by ichim** [comment]
Hello again,

The syntax of the upload() method is:

`upload(List<StreamPoint> points,  bool newCollection = false, object? pattern = null);`

The last parameter is pattern, but for upload work only PointSymbol sorry!

The only possibility to use icons is through Appearance()/AppearanceOnType(). 

I want to understand why AppearanceOnType() does not work!

Can you send me a pair of coordinates and an icon?

**Comment by paoc77** [comment]
Hi, sure
"latitude": 4.58577483333333,
"longitude": -74.1543655,
![car](https://github.com/user-attachments/assets/1028cd57-499d-4919-b904-ac21741ef4e9)

Thanks

**Comment by ichim** [comment]
Sorry for delay, sir. It's a bug. Next version of the package will fix it. SORRY

**Comment by ichim** [comment]
Hello sir,

In a few minutes, version 2.2.0 will be available, which fixes the bug you reported.

Thank you for patience!

**Comment by paoc77** [comment]
Thank you for your support, very nice work :)
