### ISSUE TITLE
Issue when rendering the map

### ISSUE THREAD

**Issue by xm3khs** [ichim/LeafletForBlazor-NuGet#52]
After the update to version 2.2.0.8, while testing, I experienced the following issue:
![image](https://github.com/user-attachments/assets/06869abe-872f-4c1e-8f87-68a87f2c5539)

export const settingsOfRendering = e => {
 let o = m(e, LeafletCore);
 onAppearanceChange(o.symbols) 
};

On Map.js, this function gives an exception because "o" is undefined when running the instruction onAppearanceChange(o.symbols)

**Comment by ichim** [comment]
Hello sir,

In a few minutes, version 2.2.2.0 will be available, which solves the bug reported by you!

**Comment by xm3khs** [comment]
Thanks. It works fine now.
