### ISSUE TITLE
Prevent map from zooming out when points move

### ISSUE THREAD

**Issue by Ksdmg** [ichim/LeafletForBlazor-NuGet#59]
Hello!
I don't know if I made a mistake in my logic, but I'm periodically updating the points on my map using the following method:
```
        private void UpdatePointPositions(object? sender, ElapsedEventArgs e)
        {

               // Logic to retrieve newPoints, deletedPoints and movePoints has been removed because I think it is not necessary
                if(newPoints.Count > 0)
                {
                    Task.Run(async () => await RealTimeMap.Geometric.Points.upload(newPoints)).GetAwaiter().GetResult();
                }
            }

            if(deletedPoints.Count > 0)
            {
                Task.Run(async () => await RealTimeMap.Geometric.Points.delete(deletedPoints.ToArray())).GetAwaiter().GetResult();
            }

            if(movePoints.Count > 0)
            {
                Task.Run(async () => await RealTimeMap.Geometric.Points.moveTo(movePoints.ToArray())).GetAwaiter().GetResult();
            }
        }
```
The page is rendered using `@rendermode @(new InteractiveServerRenderMode(prerender: false))`

Every time the UpdatePointPositions method runs, the map zooms out to it's initial state. How can I prevent it from zooming out?
Thanks!

**Comment by ichim** [comment]
Hello sir,

realTimeMap.Geometric.Points.changeExtentWhenMovingPoints property must be false.

**Comment by Ksdmg** [comment]
Thanks @ichim that worked for zooming out, but somehow the map jumps to the updated point. What properties do I have to set to keep the screen where it was?

**Comment by Ksdmg** [comment]
Yep that did the trick! thanks!
