### ISSUE TITLE
Error on loading map v 2.0.0.2

### ISSUE THREAD

**Issue by kekoshade13** [ichim/LeafletForBlazor-NuGet#8]
Hi ichim, I have a problem loading the map, This error occurs when I do the basic usage: `<Map width="100" height="300px"></Map>`

 blazor.webassembly.js:1 Microsoft.JSInterop.JSException: The requested module './esri_interops.js' does not provide an export named '_init_esri_basemap_layers' SyntaxError: The requested module './esri_interops.js' does not provide an export named '_init_esri_basemap_layers' at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__161[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext() at LeafletForBlazor.CoreJsInterop.LoadMapPartialAsync(ParametersInitialization parameters, ParametersInitialization esri_api_parameters, ParametersInitialization plugins_parameters, ParametersInitialization ui_controls_parameters, ParametersInitialization images_overlay, DotNetObjectReference1 dotNetObject)

**Comment by kekoshade13** [comment]
Any solution?

**Comment by ichim** [comment]
Hello sir,
You can send me your project?



Trimis de pe Outlook pentru Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by larseggan** [comment]
I have the same problem

**Comment by kekoshade13** [comment]
Quizás es un problema con las nuevas versiones de las librerias?

**Comment by larseggan** [comment]
@kekoshade13  @ichim I downgraded to nuget package 1.2.4 of LeafletForBlazor, then the problem with the missing esri js disappeared in runtime.

**Comment by ichim** [comment]
> Any solution?

I will check this.

**Comment by kekoshade13** [comment]
Thanks! :D

**Comment by SalvatoreDiFede** [comment]
Hi there!
Problem in 2.x nuget package seems related to esri_interops.js wrong content: at the moment it contains same js of helper.js

**Comment by tshoman** [comment]
Good day folks

Did you realise that for version 2.0 example he used <RealTimeMap /> component instead of <Map /> component . This tripped for a while as well until I doscovered that by chance, and now the component works for me without errors. 

Rds.

**Comment by tshoman** [comment]
He used Realtimemap component instead of Map component.

**Comment by ichim** [comment]
Hello everyone,
New version, 2.0.0.4, resolve issue/issues.
I apologize for what happened!
I greet you with respect!

**Comment by kekoshade13** [comment]
Thanks!! :D
